services:
  # 🐬 MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${PRODUCT_DB_NAME}

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      - order-mgmt-network

  # 🐘 PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB_NAME}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - order-mgmt-network

  #  🍃 MongoDB
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - order-mgmt-network



  # Config server
  ordermgmt-config:
    build:
      context: .
      dockerfile: infrastructure/ordermgmt-config/Dockerfile
    container_name: ordermgmt-config
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    networks:
      - order-mgmt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ordermgmt-config:${CONFIG_SERVER_PORT}/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

    # Eureka server
  ordermgmt-eureka:
    build:
      context: .
      dockerfile: infrastructure/ordermgmt-eureka/Dockerfile
    container_name: ordermgmt-eureka
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    networks:
      - order-mgmt-network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ordermgmt-config:${CONFIG_SERVER_PORT}
      - CONFIG_SERVER_URL=http://ordermgmt-config:8888
    depends_on:
      ordermgmt-config:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: on-failure

#Order_mgmt Product
  ordermgmt-product:
    build:
      context: .
      dockerfile: ./domain/ordermgmt-product/Dockerfile
    container_name: ordermgmt-product
    ports:
      - "${PRODUCT_MICROSERVICE_PORT}:8090"
    networks:
      - order-mgmt-network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ordermgmt-config:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ordermgmt-eureka:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:${MYSQL_PORT}/${PRODUCT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
       ordermgmt-config:
          condition: service_healthy
       ordermgmt-eureka:
          condition: service_healthy
       mysql:
         condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product-service:${PRODUCT_MICROSERVICE_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

# Order_mgmt Order
  ordermgmt-order:
    build:
      context: .
      dockerfile: ./domain/ordermgmt-orders/Dockerfile
    container_name: ordermgmt-order
    ports:
      - "${ORDERS_MICROSERVICE_PORT}:8091"
    networks:
      - order-mgmt-network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ordermgmt-config:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ordermgmt-eureka:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRESQL_PORT}/${ORDERS_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
    depends_on:
       ordermgmt-config:
          condition: service_healthy
       ordermgmt-eureka:
          condition: service_healthy
       postgres:
         condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://order-service:${ORDERS_MICROSERVICE_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

#Orders_mgmt API Gateway
  ordermgmt-api-gateway:
    build:
      context: .
      dockerfile: infrastructure/ordermgmt-gateway/Dockerfile
    container_name: ordermgmt-api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    networks:
      - order-mgmt-network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ordermgmt-config:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ordermgmt-eureka:${EUREKA_SERVER_PORT}/eureka/
    depends_on:
       ordermgmt-config:
          condition: service_healthy
       ordermgmt-eureka:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api-gateway:${API_GATEWAY_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

# Order_mgmt Users
  ordermgmt-users:
    build:
      context: .
      dockerfile: ./domain/ordermgmt-users/Dockerfile
    container_name: ordermgmt-users
    ports:
      - "${USERS_MICROSERVICE_PORT}:8092"
    networks:
      - order-mgmt-network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ordermgmt-config:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ordermgmt-eureka:${EUREKA_SERVER_PORT}/eureka/
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      ordermgmt-config:
        condition: service_healthy
      ordermgmt-eureka:
        condition: service_healthy
      mongodb:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure


networks:
  order-mgmt-network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  mongo_data:


###
  # 🔐 Keycloak
    ### keycloak:
    ### image: quay.io/keycloak/keycloak:24.0.1
    ### container_name: keycloak
    ### command: start-dev
    ### environment:
    ###  - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
    ###  - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ###  - KC_DB=postgres
    ###  - KC_DB_URL=jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME}
    ###  - KC_DB_USERNAME=${POSTGRESQL_USERNAME}
    ###  - KC_DB_PASSWORD=${POSTGRESQL_PASSWORD}
    ###  - KC_HOSTNAME_STRICT=false
    ### - KC_HTTP_ENABLED=true
    ### ports:
    ###  - "${KEYCLOAK_PORT}:8080"
    ### depends_on:
    ###  postgres:
    ###   condition: service_started
    ###healthcheck:
    ### test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
    ###  interval: 30s
    ### timeout: 10s
    ### retries: 10
    ### start_period: 60s
  ###v restart: on-failure
    ### v###  networks:
  ### - order-mgmt-network
  ####