server:
  port: 9090

spring:
  application:
    name: ordermgmt-orders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:

    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.data.jpa.repository: DEBUG
    org.hibernate.SQL: DEBUG