server:
  port: 9090

spring:
  application:
    name: ordermgmt-orders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health, beans, metrics, info, env
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
logging:
  level:

    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.data.jpa.repository: DEBUG
    org.hibernate.SQL: DEBUG